server:
  port: 8080
  address: 0.0.0.0

spring:
  #数据源
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.138.229:3306/abc?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    googleexcute: explorer
    #要打开的网址
    loginurl: http://localhost:${server.port}/swagger-ui.html
    #是否要启动时打开浏览器
    isopenurl: true

mybatis:
  configuration:
    #是否开启驼峰
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.sl.product.pojo

#配置日志
  logging:
    level:
      root: INFO
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR
    file: d:\\springboot3\\log\\demo2.log




